version: 2
jobs:
  build:
    working_directroy: ~/udemy-course/twetter
    docker:
      - image:  circleci/php:7.3.8-apache-stretch-node-browsers
        environment:
          APP_ENV: test
          DATABASE: mysql://root:root@127.0.0.1/micro-post
          MAIL_FROM: micro@micro.com
          MAILER_URL: null://localhost
      - image: circleci/mysql:8.0.3
        environment:
          MYSQL_ROOT_PASSWORD: 'root'
          MYSQL_DATBASE: micro-post
    steps:
      - checkout
      - run: 
          name: Install apt
          command: sudo apt-get install -y zlib1g-dev
      - run: 
          name: Install PHP MYSQL
          command: sudo docker-php-ext-install pdo_mysql zip
      - run:
          name: Wait for mysql
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      - run:
          name: composer
          command: sudo composer self-update
      - run:
          name: composer install
          command:  cd udemy-course/twetter && composer install -n --prefer-dist
      - run:
          name: Run Migrations
          command: php bin/console doctrine:migrations:migrate --env=test  --no-interaction --ignore-platform-reqs
      - run:
          name: run tests
          command: ./bin/phpunit